version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: challenge-postgres
    environment:
      POSTGRES_DB: weighing_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - challenge-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: apache/kafka:3.7.0
    container_name: challenge-kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT_HOST://0.0.0.0:9092,PLAINTEXT_DOCKER://0.0.0.0:9093,CONTROLLER://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_HOST://localhost:9092,PLAINTEXT_DOCKER://kafka:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_DOCKER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_HOST:PLAINTEXT,PLAINTEXT_DOCKER:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      KAFKA_LOG_RETENTION_HOURS: 168
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - challenge-network
    healthcheck:
      test: [ "CMD-SHELL", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server kafka:9093" ]
      interval: 10s
      timeout: 10s
      retries: 5

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: challenge-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093
    depends_on:
      - kafka
    networks:
      - challenge-network



  weighing-ingest-service:
    build:
      context: ./weighing-ingest-service
      dockerfile: Dockerfile
    container_name: weighing-ingest-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      KAFKA_HOST: kafka:9093
    ports:
      - "8080:8080"
    networks:
      - challenge-network
    restart: unless-stopped

  weighing-management-service:
    build:
      context: ./weighing-management-service
      dockerfile: Dockerfile
    container_name: weighing-management-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/weighing_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      KAFKA_HOST: kafka:9093
      SPRING_APPLICATION_NAME: weighing-management-service
      OTEL_ENDPOINT: http://otel:4318
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - kafka
      - otel
    networks:
      - challenge-network
    restart: unless-stopped

  weight-processor-service:
    build:
      context: ./weight-processor-service
      dockerfile: Dockerfile
    container_name: weight-processor-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      KAFKA_HOST: kafka:9093

    ports:
      - "8082:8082"
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - challenge-network
    restart: unless-stopped

  otel:
    image: grafana/otel-lgtm:0.7.1
    container_name: otel
    ports:
      - "3000:3000"
      - "4317:4317"
      - "9090:9090"
      - "4318:4318"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    networks:
      - challenge-network

networks:
  challenge-network:
    driver: bridge

volumes:
  postgres_data:
  kafka_data:
